### ISSUE TITLE
Add string deduplication to item data

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/dauntless-builder-reforged#271]
Currently there are a lot of literally the same strings in the item data

![image](https://user-images.githubusercontent.com/674705/181309726-04d8ce88-28be-4cdb-9060-437d8e113867.png)

It would be cool if we could somehow remove them (or replace them with a reference) to ease work on the localization front.

Idea would be:

Rework data in a way that allows you to define a description that is reused unless a level specifically overwrites it.

```yaml
unique_effects:
  - name: BoreusFrostSprite
    description: &boreusUeDescription >-
      After spending ammo, generate generate {{spriteGenerate}} Frost Sprites that grant your
      next attack +{{spriteDamage}} damage and minor frost damage (Max {{spriteMaxSprites}} Sprites)
    values:
      spriteGenerate: 3
      spriteDamage: 30
      spriteMaxSprites: 4
    powerSurged: false
  - name: BoreusFrostSprite # this has no description, use description from the other one?
    values:
      spriteGenerate: 3
      spriteDamage: 60
      spriteMaxSprites: 4
    powerSurged: true
```

or something akin to this, might require some thinking.
