### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by R3dL3ad3r** [atomicptr/dauntless-builder-reforged#69]
Not a real issue, but would it be possible to localize the builder in other languages?

**Comment by atomicptr** [comment]
Possible yes, but I'd imagine maintaining this to be a nightmare.

**Comment by R3dL3ad3r** [comment]
Hi there, sorry for the delay, i had some issues irl. I'm part of the localization team for the game and we would be interested in working on this builder too so the italian community can use it (sadly enough, most players find it difficult to use english material).
Please let us know if we can help you with an italian translation, we'd be happy to work on it.

**Comment by atomicptr** [comment]
Hey! This is def. something that I want to tackle with the "Dauntless Builder 2.0" rework, though I haven't had too much time recently myself.

There are generally a few approaches on how one could do this,

The most straightforward would probably having something like an overlay file that tries to load something in the requested language and should it fail, uses the english one instead, though that would mean either defining keywords like: INFERNOS_RAZOR_DESCRIPTION etc, or using the english one as a key "This weapon does.... blabla" (which sadly also has the disadvantage of breaking if the thing changes).

Such an overlay file could look like this:

```yaml
# de.translations.yml
translations:
   "Infernos Razor": Brennendes Schwert # not the actual name

# or in the more key based approach
translations:
  INFERNOS_RAZOR: Brennendes Schwert
```

Or defining everything in the original file as well like this:

```yaml
name:
  en: Infernos Razor
  de: Ein deutscher Name der mir nicht bekannt ist
  fr: etc etc
description:
  en: ...
````

Beyond me needing to find time, I'll obviously also have to find a format that a contributor (like yourself maybe) could work with.
